#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JabbrMobile.Resource", IsApplication=true)]

namespace JabbrMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::JabbrMobile.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::JabbrMobile.Resource.String.Hello;
			global::AndroidHUD.Resource.Attribute.barColor = global::JabbrMobile.Resource.Attribute.barColor;
			global::AndroidHUD.Resource.Attribute.barLength = global::JabbrMobile.Resource.Attribute.barLength;
			global::AndroidHUD.Resource.Attribute.barWidth = global::JabbrMobile.Resource.Attribute.barWidth;
			global::AndroidHUD.Resource.Attribute.circleColor = global::JabbrMobile.Resource.Attribute.circleColor;
			global::AndroidHUD.Resource.Attribute.delayMillis = global::JabbrMobile.Resource.Attribute.delayMillis;
			global::AndroidHUD.Resource.Attribute.radius = global::JabbrMobile.Resource.Attribute.radius;
			global::AndroidHUD.Resource.Attribute.rimColor = global::JabbrMobile.Resource.Attribute.rimColor;
			global::AndroidHUD.Resource.Attribute.rimWidth = global::JabbrMobile.Resource.Attribute.rimWidth;
			global::AndroidHUD.Resource.Attribute.spinSpeed = global::JabbrMobile.Resource.Attribute.spinSpeed;
			global::AndroidHUD.Resource.Attribute.text = global::JabbrMobile.Resource.Attribute.text;
			global::AndroidHUD.Resource.Attribute.textColor = global::JabbrMobile.Resource.Attribute.textColor;
			global::AndroidHUD.Resource.Attribute.textSize = global::JabbrMobile.Resource.Attribute.textSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::JabbrMobile.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::JabbrMobile.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::JabbrMobile.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::JabbrMobile.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::JabbrMobile.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::JabbrMobile.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::JabbrMobile.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::JabbrMobile.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::JabbrMobile.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::JabbrMobile.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::JabbrMobile.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::JabbrMobile.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::JabbrMobile.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barColor = global::JabbrMobile.Resource.Styleable.ProgressWheel_barColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barLength = global::JabbrMobile.Resource.Styleable.ProgressWheel_barLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barWidth = global::JabbrMobile.Resource.Styleable.ProgressWheel_barWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_circleColor = global::JabbrMobile.Resource.Styleable.ProgressWheel_circleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_delayMillis = global::JabbrMobile.Resource.Styleable.ProgressWheel_delayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_radius = global::JabbrMobile.Resource.Styleable.ProgressWheel_radius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimColor = global::JabbrMobile.Resource.Styleable.ProgressWheel_rimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimWidth = global::JabbrMobile.Resource.Styleable.ProgressWheel_rimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_spinSpeed = global::JabbrMobile.Resource.Styleable.ProgressWheel_spinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_text = global::JabbrMobile.Resource.Styleable.ProgressWheel_text;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textColor = global::JabbrMobile.Resource.Styleable.ProgressWheel_textColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textSize = global::JabbrMobile.Resource.Styleable.ProgressWheel_textSize;
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::JabbrMobile.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::JabbrMobile.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::JabbrMobile.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::JabbrMobile.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::JabbrMobile.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::JabbrMobile.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::JabbrMobile.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::JabbrMobile.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::JabbrMobile.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::JabbrMobile.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::JabbrMobile.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::JabbrMobile.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::JabbrMobile.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::JabbrMobile.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::JabbrMobile.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::JabbrMobile.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::JabbrMobile.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::JabbrMobile.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::JabbrMobile.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::JabbrMobile.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::JabbrMobile.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::JabbrMobile.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::JabbrMobile.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::JabbrMobile.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::JabbrMobile.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::JabbrMobile.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::JabbrMobile.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::JabbrMobile.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::JabbrMobile.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::JabbrMobile.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::JabbrMobile.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::JabbrMobile.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::JabbrMobile.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::JabbrMobile.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::JabbrMobile.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::JabbrMobile.Resource.Styleable.SlidingMenu_viewBehind;
			global::JabbrMobile.Common.Resource.String.library_name = global::JabbrMobile.Resource.String.library_name;
			global::LegacyBar.Library.Resource.Attribute.background = global::JabbrMobile.Resource.Attribute.background;
			global::LegacyBar.Library.Resource.Attribute.background_item = global::JabbrMobile.Resource.Attribute.background_item;
			global::LegacyBar.Library.Resource.Attribute.is_bottom = global::JabbrMobile.Resource.Attribute.is_bottom;
			global::LegacyBar.Library.Resource.Attribute.light_icons = global::JabbrMobile.Resource.Attribute.light_icons;
			global::LegacyBar.Library.Resource.Attribute.separator = global::JabbrMobile.Resource.Attribute.separator;
			global::LegacyBar.Library.Resource.Attribute.theme = global::JabbrMobile.Resource.Attribute.theme;
			global::LegacyBar.Library.Resource.Attribute.title = global::JabbrMobile.Resource.Attribute.title;
			global::LegacyBar.Library.Resource.Attribute.title_color = global::JabbrMobile.Resource.Attribute.title_color;
			global::LegacyBar.Library.Resource.Color.Red = global::JabbrMobile.Resource.Color.Red;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = global::JabbrMobile.Resource.Color.actionbar_accentcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = global::JabbrMobile.Resource.Color.actionbar_accentcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkblue = global::JabbrMobile.Resource.Color.actionbar_accentcolor_darkblue;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = global::JabbrMobile.Resource.Color.actionbar_accentcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = global::JabbrMobile.Resource.Color.actionbar_accentcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end = global::JabbrMobile.Resource.Color.actionbar_background_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end_alt = global::JabbrMobile.Resource.Color.actionbar_background_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = global::JabbrMobile.Resource.Color.actionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = global::JabbrMobile.Resource.Color.actionbar_background_item_pressed_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = global::JabbrMobile.Resource.Color.actionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = global::JabbrMobile.Resource.Color.actionbar_background_item_pressed_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start = global::JabbrMobile.Resource.Color.actionbar_background_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start_alt = global::JabbrMobile.Resource.Color.actionbar_background_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_black = global::JabbrMobile.Resource.Color.actionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = global::JabbrMobile.Resource.Color.actionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_darkblue = global::JabbrMobile.Resource.Color.actionbar_maincolor_darkblue;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = global::JabbrMobile.Resource.Color.actionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = global::JabbrMobile.Resource.Color.actionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = global::JabbrMobile.Resource.Color.actionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = global::JabbrMobile.Resource.Color.actionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkblue = global::JabbrMobile.Resource.Color.actionbar_pressedcolor_darkblue;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = global::JabbrMobile.Resource.Color.actionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = global::JabbrMobile.Resource.Color.actionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator = global::JabbrMobile.Resource.Color.actionbar_separator;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_alt = global::JabbrMobile.Resource.Color.actionbar_separator_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_black = global::JabbrMobile.Resource.Color.actionbar_separator_black;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_blue = global::JabbrMobile.Resource.Color.actionbar_separator_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_darkblue = global::JabbrMobile.Resource.Color.actionbar_separator_darkblue;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = global::JabbrMobile.Resource.Color.actionbar_separator_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = global::JabbrMobile.Resource.Color.actionbar_separator_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title = global::JabbrMobile.Resource.Color.actionbar_title;
			global::LegacyBar.Library.Resource.Color.actionbar_title_alt = global::JabbrMobile.Resource.Color.actionbar_title_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_title_black = global::JabbrMobile.Resource.Color.actionbar_title_black;
			global::LegacyBar.Library.Resource.Color.actionbar_title_blue = global::JabbrMobile.Resource.Color.actionbar_title_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_title_darkblue = global::JabbrMobile.Resource.Color.actionbar_title_darkblue;
			global::LegacyBar.Library.Resource.Color.actionbar_title_darkgray = global::JabbrMobile.Resource.Color.actionbar_title_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title_lightgray = global::JabbrMobile.Resource.Color.actionbar_title_lightgray;
			global::LegacyBar.Library.Resource.Color.black = global::JabbrMobile.Resource.Color.black;
			global::LegacyBar.Library.Resource.Color.blue = global::JabbrMobile.Resource.Color.blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_end = global::JabbrMobile.Resource.Color.bottomactionbar_background_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = global::JabbrMobile.Resource.Color.bottomactionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = global::JabbrMobile.Resource.Color.bottomactionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_start = global::JabbrMobile.Resource.Color.bottomactionbar_background_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = global::JabbrMobile.Resource.Color.bottomactionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = global::JabbrMobile.Resource.Color.bottomactionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkblue = global::JabbrMobile.Resource.Color.bottomactionbar_maincolor_darkblue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = global::JabbrMobile.Resource.Color.bottomactionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = global::JabbrMobile.Resource.Color.bottomactionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = global::JabbrMobile.Resource.Color.bottomactionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = global::JabbrMobile.Resource.Color.bottomactionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkblue = global::JabbrMobile.Resource.Color.bottomactionbar_pressedcolor_darkblue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = global::JabbrMobile.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = global::JabbrMobile.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_separator = global::JabbrMobile.Resource.Color.bottomactionbar_separator;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_title = global::JabbrMobile.Resource.Color.bottomactionbar_title;
			global::LegacyBar.Library.Resource.Color.green = global::JabbrMobile.Resource.Color.green;
			global::LegacyBar.Library.Resource.Color.grey = global::JabbrMobile.Resource.Color.grey;
			global::LegacyBar.Library.Resource.Color.pager_black = global::JabbrMobile.Resource.Color.pager_black;
			global::LegacyBar.Library.Resource.Color.pager_blue = global::JabbrMobile.Resource.Color.pager_blue;
			global::LegacyBar.Library.Resource.Color.pager_darkblue = global::JabbrMobile.Resource.Color.pager_darkblue;
			global::LegacyBar.Library.Resource.Color.pager_darkgray = global::JabbrMobile.Resource.Color.pager_darkgray;
			global::LegacyBar.Library.Resource.Color.pager_lightgray = global::JabbrMobile.Resource.Color.pager_lightgray;
			global::LegacyBar.Library.Resource.Color.red = global::JabbrMobile.Resource.Color.red;
			global::LegacyBar.Library.Resource.Color.white = global::JabbrMobile.Resource.Color.white;
			global::LegacyBar.Library.Resource.Color.yellow = global::JabbrMobile.Resource.Color.yellow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_accentheight = global::JabbrMobile.Resource.Dimension.actionbar_accentheight;
			global::LegacyBar.Library.Resource.Dimension.actionbar_height = global::JabbrMobile.Resource.Dimension.actionbar_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = global::JabbrMobile.Resource.Dimension.actionbar_home_item_width;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height = global::JabbrMobile.Resource.Dimension.actionbar_item_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = global::JabbrMobile.Resource.Dimension.actionbar_item_height_over;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = global::JabbrMobile.Resource.Dimension.actionbar_item_height_overflow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_width = global::JabbrMobile.Resource.Dimension.actionbar_item_width;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = global::JabbrMobile.Resource.Drawable.actionbar_back_indicator;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = global::JabbrMobile.Resource.Drawable.actionbar_back_indicator_dark;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background = global::JabbrMobile.Resource.Drawable.actionbar_background;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_alt = global::JabbrMobile.Resource.Drawable.actionbar_background_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_black = global::JabbrMobile.Resource.Drawable.actionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_blue = global::JabbrMobile.Resource.Drawable.actionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_darkblue = global::JabbrMobile.Resource.Drawable.actionbar_background_darkblue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = global::JabbrMobile.Resource.Drawable.actionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = global::JabbrMobile.Resource.Drawable.actionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn = global::JabbrMobile.Resource.Drawable.actionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = global::JabbrMobile.Resource.Drawable.actionbar_btn_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_black = global::JabbrMobile.Resource.Drawable.actionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = global::JabbrMobile.Resource.Drawable.actionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_darkblue = global::JabbrMobile.Resource.Drawable.actionbar_btn_darkblue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = global::JabbrMobile.Resource.Drawable.actionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = global::JabbrMobile.Resource.Drawable.actionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = global::JabbrMobile.Resource.Drawable.actionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = global::JabbrMobile.Resource.Drawable.actionbar_btn_normal_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = global::JabbrMobile.Resource.Drawable.actionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = global::JabbrMobile.Resource.Drawable.actionbar_btn_pressed_alt;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background = global::JabbrMobile.Resource.Drawable.bottomactionbar_background;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = global::JabbrMobile.Resource.Drawable.bottomactionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = global::JabbrMobile.Resource.Drawable.bottomactionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkblue = global::JabbrMobile.Resource.Drawable.bottomactionbar_background_darkblue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = global::JabbrMobile.Resource.Drawable.bottomactionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = global::JabbrMobile.Resource.Drawable.bottomactionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkblue = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_darkblue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = global::JabbrMobile.Resource.Drawable.bottomactionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = global::JabbrMobile.Resource.Drawable.dropdown_btn_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = global::JabbrMobile.Resource.Drawable.dropdown_btn_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = global::JabbrMobile.Resource.Drawable.dropdown_disabled_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = global::JabbrMobile.Resource.Drawable.dropdown_disabled_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = global::JabbrMobile.Resource.Drawable.dropdown_focused_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = global::JabbrMobile.Resource.Drawable.dropdown_focused_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = global::JabbrMobile.Resource.Drawable.dropdown_normal_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = global::JabbrMobile.Resource.Drawable.dropdown_normal_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = global::JabbrMobile.Resource.Drawable.dropdown_pressed_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = global::JabbrMobile.Resource.Drawable.dropdown_pressed_holo_light;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow = global::JabbrMobile.Resource.Drawable.ic_action_overflow;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = global::JabbrMobile.Resource.Drawable.ic_action_overflow_dark;
			global::LegacyBar.Library.Resource.Id.actionbar_actions = global::JabbrMobile.Resource.Id.actionbar_actions;
			global::LegacyBar.Library.Resource.Id.actionbar_home = global::JabbrMobile.Resource.Id.actionbar_home;
			global::LegacyBar.Library.Resource.Id.actionbar_home_bg = global::JabbrMobile.Resource.Id.actionbar_home_bg;
			global::LegacyBar.Library.Resource.Id.actionbar_home_btn = global::JabbrMobile.Resource.Id.actionbar_home_btn;
			global::LegacyBar.Library.Resource.Id.actionbar_home_is_back = global::JabbrMobile.Resource.Id.actionbar_home_is_back;
			global::LegacyBar.Library.Resource.Id.actionbar_home_logo = global::JabbrMobile.Resource.Id.actionbar_home_logo;
			global::LegacyBar.Library.Resource.Id.actionbar_item = global::JabbrMobile.Resource.Id.actionbar_item;
			global::LegacyBar.Library.Resource.Id.actionbar_progress = global::JabbrMobile.Resource.Id.actionbar_progress;
			global::LegacyBar.Library.Resource.Id.actionbar_spinner = global::JabbrMobile.Resource.Id.actionbar_spinner;
			global::LegacyBar.Library.Resource.Id.actionbar_title = global::JabbrMobile.Resource.Id.actionbar_title;
			global::LegacyBar.Library.Resource.Id.actionbar_title_layout = global::JabbrMobile.Resource.Id.actionbar_title_layout;
			global::LegacyBar.Library.Resource.Id.custom = global::JabbrMobile.Resource.Id.custom;
			global::LegacyBar.Library.Resource.Id.holo_black = global::JabbrMobile.Resource.Id.holo_black;
			global::LegacyBar.Library.Resource.Id.holo_blue = global::JabbrMobile.Resource.Id.holo_blue;
			global::LegacyBar.Library.Resource.Id.holo_darkblue = global::JabbrMobile.Resource.Id.holo_darkblue;
			global::LegacyBar.Library.Resource.Id.holo_gray = global::JabbrMobile.Resource.Id.holo_gray;
			global::LegacyBar.Library.Resource.Id.holo_light = global::JabbrMobile.Resource.Id.holo_light;
			global::LegacyBar.Library.Resource.Id.overflow_spinner = global::JabbrMobile.Resource.Id.overflow_spinner;
			global::LegacyBar.Library.Resource.Id.screen = global::JabbrMobile.Resource.Id.screen;
			global::LegacyBar.Library.Resource.Layout.actionbar = global::JabbrMobile.Resource.Layout.actionbar;
			global::LegacyBar.Library.Resource.Layout.actionbar_item = global::JabbrMobile.Resource.Layout.actionbar_item;
			global::LegacyBar.Library.Resource.Layout.blankspinner = global::JabbrMobile.Resource.Layout.blankspinner;
			global::LegacyBar.Library.Resource.Layout.overflowactionbar_item = global::JabbrMobile.Resource.Layout.overflowactionbar_item;
			global::LegacyBar.Library.Resource.Layout.spinneritem = global::JabbrMobile.Resource.Layout.spinneritem;
			global::LegacyBar.Library.Resource.String.actionbar_activity_not_found = global::JabbrMobile.Resource.String.actionbar_activity_not_found;
			global::LegacyBar.Library.Resource.Style.actionbar = global::JabbrMobile.Resource.Style.actionbar;
			global::LegacyBar.Library.Resource.Style.actionbarhomeitem = global::JabbrMobile.Resource.Style.actionbarhomeitem;
			global::LegacyBar.Library.Resource.Style.actionbarhomelogo = global::JabbrMobile.Resource.Style.actionbarhomelogo;
			global::LegacyBar.Library.Resource.Style.actionbaritem = global::JabbrMobile.Resource.Style.actionbaritem;
			global::LegacyBar.Library.Resource.Style.actionbarprogressbar = global::JabbrMobile.Resource.Style.actionbarprogressbar;
			global::LegacyBar.Library.Resource.Style.clearbutton = global::JabbrMobile.Resource.Style.clearbutton;
			global::LegacyBar.Library.Resource.Styleable.actionbar = global::JabbrMobile.Resource.Styleable.actionbar;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background = global::JabbrMobile.Resource.Styleable.actionbar_background;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background_item = global::JabbrMobile.Resource.Styleable.actionbar_background_item;
			global::LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = global::JabbrMobile.Resource.Styleable.actionbar_is_bottom;
			global::LegacyBar.Library.Resource.Styleable.actionbar_light_icons = global::JabbrMobile.Resource.Styleable.actionbar_light_icons;
			global::LegacyBar.Library.Resource.Styleable.actionbar_separator = global::JabbrMobile.Resource.Styleable.actionbar_separator;
			global::LegacyBar.Library.Resource.Styleable.actionbar_theme = global::JabbrMobile.Resource.Styleable.actionbar_theme;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title = global::JabbrMobile.Resource.Styleable.actionbar_title;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title_color = global::JabbrMobile.Resource.Styleable.actionbar_title_color;
			global::JabbR.Client.Android.Resource.String.library_name = global::JabbrMobile.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010022
			public const int MvxBind = 2130772002;
			
			// aapt resource value: 0x7f010024
			public const int MvxDropDownItemTemplate = 2130772004;
			
			// aapt resource value: 0x7f010023
			public const int MvxItemTemplate = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int MvxSource = 2130772005;
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010019
			public const int barColor = 2130771993;
			
			// aapt resource value: 0x7f010021
			public const int barLength = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int barWidth = 2130772000;
			
			// aapt resource value: 0x7f01000b
			public const int behindOffset = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int behindScrollScale = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int behindWidth = 2130771980;
			
			// aapt resource value: 0x7f01001e
			public const int circleColor = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int delayMillis = 2130771997;
			
			// aapt resource value: 0x7f010013
			public const int fadeDegree = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fadeEnabled = 2130771986;
			
			// aapt resource value: 0x7f010006
			public const int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int mode = 2130771976;
			
			// aapt resource value: 0x7f01001f
			public const int radius = 2130771999;
			
			// aapt resource value: 0x7f01001a
			public const int rimColor = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int rimWidth = 2130771995;
			
			// aapt resource value: 0x7f010015
			public const int selectorDrawable = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int selectorEnabled = 2130771988;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010010
			public const int shadowDrawable = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int shadowWidth = 2130771985;
			
			// aapt resource value: 0x7f01001c
			public const int spinSpeed = 2130771996;
			
			// aapt resource value: 0x7f010016
			public const int text = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int textColor = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int textSize = 2130771992;
			
			// aapt resource value: 0x7f010005
			public const int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			// aapt resource value: 0x7f01000e
			public const int touchModeAbove = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int touchModeBehind = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int viewAbove = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int viewBehind = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060041
			public const int Red = 2131099713;
			
			// aapt resource value: 0x7f060023
			public const int actionbar_accentcolor_black = 2131099683;
			
			// aapt resource value: 0x7f06002b
			public const int actionbar_accentcolor_blue = 2131099691;
			
			// aapt resource value: 0x7f060033
			public const int actionbar_accentcolor_darkblue = 2131099699;
			
			// aapt resource value: 0x7f06001b
			public const int actionbar_accentcolor_darkgray = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int actionbar_accentcolor_lightgray = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_background_end = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int actionbar_background_end_alt = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_background_item_pressed_end = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int actionbar_background_item_pressed_end_alt = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_background_item_pressed_start = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int actionbar_background_item_pressed_start_alt = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_background_start = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int actionbar_background_start_alt = 2131099656;
			
			// aapt resource value: 0x7f060022
			public const int actionbar_maincolor_black = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int actionbar_maincolor_blue = 2131099690;
			
			// aapt resource value: 0x7f060032
			public const int actionbar_maincolor_darkblue = 2131099698;
			
			// aapt resource value: 0x7f06001a
			public const int actionbar_maincolor_darkgray = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int actionbar_maincolor_lightgray = 2131099666;
			
			// aapt resource value: 0x7f060024
			public const int actionbar_pressedcolor_black = 2131099684;
			
			// aapt resource value: 0x7f06002c
			public const int actionbar_pressedcolor_blue = 2131099692;
			
			// aapt resource value: 0x7f060034
			public const int actionbar_pressedcolor_darkblue = 2131099700;
			
			// aapt resource value: 0x7f06001c
			public const int actionbar_pressedcolor_darkgray = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int actionbar_pressedcolor_lightgray = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int actionbar_separator = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_separator_alt = 2131099654;
			
			// aapt resource value: 0x7f060026
			public const int actionbar_separator_black = 2131099686;
			
			// aapt resource value: 0x7f06002e
			public const int actionbar_separator_blue = 2131099694;
			
			// aapt resource value: 0x7f060036
			public const int actionbar_separator_darkblue = 2131099702;
			
			// aapt resource value: 0x7f06001e
			public const int actionbar_separator_darkgray = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int actionbar_separator_lightgray = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_title = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int actionbar_title_alt = 2131099655;
			
			// aapt resource value: 0x7f060025
			public const int actionbar_title_black = 2131099685;
			
			// aapt resource value: 0x7f06002d
			public const int actionbar_title_blue = 2131099693;
			
			// aapt resource value: 0x7f060035
			public const int actionbar_title_darkblue = 2131099701;
			
			// aapt resource value: 0x7f06001d
			public const int actionbar_title_darkgray = 2131099677;
			
			// aapt resource value: 0x7f060015
			public const int actionbar_title_lightgray = 2131099669;
			
			// aapt resource value: 0x7f06003b
			public const int black = 2131099707;
			
			// aapt resource value: 0x7f06003e
			public const int blue = 2131099710;
			
			// aapt resource value: 0x7f06000f
			public const int bottomactionbar_background_end = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int bottomactionbar_background_item_pressed_end = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int bottomactionbar_background_item_pressed_start = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int bottomactionbar_background_start = 2131099662;
			
			// aapt resource value: 0x7f060027
			public const int bottomactionbar_maincolor_black = 2131099687;
			
			// aapt resource value: 0x7f06002f
			public const int bottomactionbar_maincolor_blue = 2131099695;
			
			// aapt resource value: 0x7f060037
			public const int bottomactionbar_maincolor_darkblue = 2131099703;
			
			// aapt resource value: 0x7f06001f
			public const int bottomactionbar_maincolor_darkgray = 2131099679;
			
			// aapt resource value: 0x7f060017
			public const int bottomactionbar_maincolor_lightgray = 2131099671;
			
			// aapt resource value: 0x7f060028
			public const int bottomactionbar_pressedcolor_black = 2131099688;
			
			// aapt resource value: 0x7f060030
			public const int bottomactionbar_pressedcolor_blue = 2131099696;
			
			// aapt resource value: 0x7f060038
			public const int bottomactionbar_pressedcolor_darkblue = 2131099704;
			
			// aapt resource value: 0x7f060020
			public const int bottomactionbar_pressedcolor_darkgray = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int bottomactionbar_pressedcolor_lightgray = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int bottomactionbar_separator = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int bottomactionbar_title = 2131099661;
			
			// aapt resource value: 0x7f06003c
			public const int green = 2131099708;
			
			// aapt resource value: 0x7f06003f
			public const int grey = 2131099711;
			
			// aapt resource value: 0x7f060042
			public const int menuhighlight = 2131099714;
			
			// aapt resource value: 0x7f060029
			public const int pager_black = 2131099689;
			
			// aapt resource value: 0x7f060031
			public const int pager_blue = 2131099697;
			
			// aapt resource value: 0x7f060039
			public const int pager_darkblue = 2131099705;
			
			// aapt resource value: 0x7f060021
			public const int pager_darkgray = 2131099681;
			
			// aapt resource value: 0x7f060019
			public const int pager_lightgray = 2131099673;
			
			// aapt resource value: 0x7f06003d
			public const int red = 2131099709;
			
			// aapt resource value: 0x7f06003a
			public const int white = 2131099706;
			
			// aapt resource value: 0x7f060040
			public const int yellow = 2131099712;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar_accentheight = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int actionbar_height = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int actionbar_home_item_width = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int actionbar_item_height = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int actionbar_item_height_over = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int actionbar_item_height_overflow = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actionbar_item_width = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_darkblue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_darkgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_background_lightgray = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_btn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn_alt = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_black = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_darkblue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_darkgray = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_lightgray = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_normal_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int actionbar_btn_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int actionbar_btn_pressed_alt = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_black = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_background_darkblue = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_background_darkgray = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_background_lightgray = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_black = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_blue = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_darkblue = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bottomactionbar_btn_darkgray = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bottomactionbar_btn_lightgray = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bottomactionbar_btn_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bottomactionbar_btn_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ButtonGlowLight = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dropdown_btn_holo_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dropdown_btn_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dropdown_disabled_holo_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dropdown_disabled_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dropdown_focused_holo_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dropdown_focused_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dropdown_normal_holo_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dropdown_normal_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dropdown_pressed_holo_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dropdown_pressed_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_down = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_down_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_left = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_left_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_overflow = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_overflow_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_refresh = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_refresh_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_right = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_right_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_search = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_search_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_share = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_action_share_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_action_sort = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_action_sort_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_up = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_up_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_errorstatus = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_menu_down = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_menu_left = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_menu_refresh = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_menu_right = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_menu_search = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_menu_up = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_successstatus = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Icon = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int icon_accounts = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int icon_add = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int icon_delete = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icon_exit = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int icon_green_circle_small = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int icon_save = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icon_settings = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int icon_users_grey = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int icon_yellow_circle_small = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int jabbr_bg = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int jabbr_home_icon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int launchericon = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ListItem_Menu_Room_Selector = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int loadingbar = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int roundedbg = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int roundedbgdark = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int SlidingMenuShadow = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int SlidingMenuShadowRight = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int status_green = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int status_yellow = 2130837595;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int MvxBindingTagUnique = 2131034123;
			
			// aapt resource value: 0x7f050018
			public const int actionbar = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_actions = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int actionbar_home = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int actionbar_home_bg = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int actionbar_home_btn = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int actionbar_home_is_back = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int actionbar_home_logo = 2131034126;
			
			// aapt resource value: 0x7f050017
			public const int actionbar_item = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_progress = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_spinner = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_title_layout = 2131034131;
			
			// aapt resource value: 0x7f05001c
			public const int chatText = 2131034140;
			
			// aapt resource value: 0x7f050037
			public const int checkBox1 = 2131034167;
			
			// aapt resource value: 0x7f050019
			public const int content_frame = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int custom = 2131034112;
			
			// aapt resource value: 0x7f050032
			public const int editText1 = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int editText2 = 2131034164;
			
			// aapt resource value: 0x7f050036
			public const int editText3 = 2131034166;
			
			// aapt resource value: 0x7f050009
			public const int fullscreen = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int holo_black = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int holo_blue = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int holo_darkblue = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int holo_gray = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int holo_light = 2131034113;
			
			// aapt resource value: 0x7f05001d
			public const int imageView1 = 2131034141;
			
			// aapt resource value: 0x7f050025
			public const int imageView2 = 2131034149;
			
			// aapt resource value: 0x7f050006
			public const int left = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout1 = 2131034139;
			
			// aapt resource value: 0x7f050028
			public const int loadingBar = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int loadingBarMessage = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int loadingImage = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int loadingProgressBar = 2131034150;
			
			// aapt resource value: 0x7f05002b
			public const int loadingProgressWheel = 2131034155;
			
			// aapt resource value: 0x7f050008
			public const int margin = 2131034120;
			
			// aapt resource value: 0x7f050038
			public const int menu_add = 2131034168;
			
			// aapt resource value: 0x7f05003b
			public const int menu_connection = 2131034171;
			
			// aapt resource value: 0x7f050039
			public const int menu_delete = 2131034169;
			
			// aapt resource value: 0x7f05002c
			public const int menu_frame = 2131034156;
			
			// aapt resource value: 0x7f05003c
			public const int menu_leave_room = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int menu_save = 2131034170;
			
			// aapt resource value: 0x7f050030
			public const int mvxListViewAccounts = 2131034160;
			
			// aapt resource value: 0x7f05001a
			public const int mvxListViewMessages = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int mvxListViewRooms = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int mvxListViewUsers = 2131034143;
			
			// aapt resource value: 0x7f05002d
			public const int overflow_spinner = 2131034157;
			
			// aapt resource value: 0x7f050007
			public const int right = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int screen = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int selected_view = 2131034122;
			
			// aapt resource value: 0x7f05002e
			public const int slidingmenumain = 2131034158;
			
			// aapt resource value: 0x7f050031
			public const int textView1 = 2131034161;
			
			// aapt resource value: 0x7f050033
			public const int textView2 = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int textView3 = 2131034165;
			
			// aapt resource value: 0x7f050023
			public const int textViewMessageBody = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int textViewMessageUser = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int textViewRoomName = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int textViewServer = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int textViewStatus = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int userlist_frame = 2131034159;
			
			// aapt resource value: 0x7f050024
			public const int view1 = 2131034148;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Content_Frame = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_Chat = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_Empty = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_UserList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem_Account = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListItem_Chat = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListItem_Menu_Room = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ListItem_Menu_User = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ListItem_Room = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int loading = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LoadingBar = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int loadingimage = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int loadingprogress = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Menu_Frame = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int overflowactionbar_item = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int slidingmenumain = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int spinneritem = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int UserList_Frame = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int View_Accounts = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int View_EditAccount = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int View_RoomList = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int AccountsMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int EditAccountMenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int HomeMenu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_activity_not_found = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int menu_string_delete = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int menu_string_down = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int menu_string_exit = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int menu_string_left = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int menu_string_refresh = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int menu_string_right = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int menu_string_save = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int menu_string_search = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int menu_string_sort = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int menu_string_up = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int some_title = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080006
			public const int LoadingBar = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MyTheme = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130772002};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130772005};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130772003,
					2130772004};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 3
			public const int ProgressWheel_barColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_barLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_barWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_circleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_delayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_radius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_rimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_rimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_spinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_text = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_textColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_textSize = 2;
			
			public static int[] SlidingMenu = new int[]
			{
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			public static int[] actionbar = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
