#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JabbrMobile.Android.Resource", IsApplication=true)]

namespace JabbrMobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			SlidingMenuSharp.Resource.Attribute.behindOffset = JabbrMobile.Android.Resource.Attribute.behindOffset;
			SlidingMenuSharp.Resource.Attribute.behindScrollScale = JabbrMobile.Android.Resource.Attribute.behindScrollScale;
			SlidingMenuSharp.Resource.Attribute.behindWidth = JabbrMobile.Android.Resource.Attribute.behindWidth;
			SlidingMenuSharp.Resource.Attribute.fadeDegree = JabbrMobile.Android.Resource.Attribute.fadeDegree;
			SlidingMenuSharp.Resource.Attribute.fadeEnabled = JabbrMobile.Android.Resource.Attribute.fadeEnabled;
			SlidingMenuSharp.Resource.Attribute.mode = JabbrMobile.Android.Resource.Attribute.mode;
			SlidingMenuSharp.Resource.Attribute.selectorDrawable = JabbrMobile.Android.Resource.Attribute.selectorDrawable;
			SlidingMenuSharp.Resource.Attribute.selectorEnabled = JabbrMobile.Android.Resource.Attribute.selectorEnabled;
			SlidingMenuSharp.Resource.Attribute.shadowDrawable = JabbrMobile.Android.Resource.Attribute.shadowDrawable;
			SlidingMenuSharp.Resource.Attribute.shadowWidth = JabbrMobile.Android.Resource.Attribute.shadowWidth;
			SlidingMenuSharp.Resource.Attribute.touchModeAbove = JabbrMobile.Android.Resource.Attribute.touchModeAbove;
			SlidingMenuSharp.Resource.Attribute.touchModeBehind = JabbrMobile.Android.Resource.Attribute.touchModeBehind;
			SlidingMenuSharp.Resource.Attribute.viewAbove = JabbrMobile.Android.Resource.Attribute.viewAbove;
			SlidingMenuSharp.Resource.Attribute.viewBehind = JabbrMobile.Android.Resource.Attribute.viewBehind;
			SlidingMenuSharp.Resource.Id.fullscreen = JabbrMobile.Android.Resource.Id.fullscreen;
			SlidingMenuSharp.Resource.Id.left = JabbrMobile.Android.Resource.Id.left;
			SlidingMenuSharp.Resource.Id.margin = JabbrMobile.Android.Resource.Id.margin;
			SlidingMenuSharp.Resource.Id.right = JabbrMobile.Android.Resource.Id.right;
			SlidingMenuSharp.Resource.Id.selected_view = JabbrMobile.Android.Resource.Id.selected_view;
			SlidingMenuSharp.Resource.Id.slidingmenumain = JabbrMobile.Android.Resource.Id.slidingmenumain;
			SlidingMenuSharp.Resource.Layout.slidingmenumain = JabbrMobile.Android.Resource.Layout.slidingmenumain;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu = JabbrMobile.Android.Resource.Styleable.SlidingMenu;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindOffset;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindScrollScale;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindWidth;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = JabbrMobile.Android.Resource.Styleable.SlidingMenu_fadeDegree;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = JabbrMobile.Android.Resource.Styleable.SlidingMenu_fadeEnabled;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = JabbrMobile.Android.Resource.Styleable.SlidingMenu_mode;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = JabbrMobile.Android.Resource.Styleable.SlidingMenu_selectorDrawable;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = JabbrMobile.Android.Resource.Styleable.SlidingMenu_selectorEnabled;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = JabbrMobile.Android.Resource.Styleable.SlidingMenu_shadowDrawable;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = JabbrMobile.Android.Resource.Styleable.SlidingMenu_shadowWidth;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = JabbrMobile.Android.Resource.Styleable.SlidingMenu_touchModeAbove;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = JabbrMobile.Android.Resource.Styleable.SlidingMenu_touchModeBehind;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = JabbrMobile.Android.Resource.Styleable.SlidingMenu_viewAbove;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = JabbrMobile.Android.Resource.Styleable.SlidingMenu_viewBehind;
			JabbrMobile.Common.Resource.String.library_name = JabbrMobile.Android.Resource.String.library_name;
			JabbR.Client.Android.Resource.String.library_name = JabbrMobile.Android.Resource.String.library_name;
			LegacyBar.Library.Resource.Attribute.background = JabbrMobile.Android.Resource.Attribute.background;
			LegacyBar.Library.Resource.Attribute.background_item = JabbrMobile.Android.Resource.Attribute.background_item;
			LegacyBar.Library.Resource.Attribute.is_bottom = JabbrMobile.Android.Resource.Attribute.is_bottom;
			LegacyBar.Library.Resource.Attribute.light_icons = JabbrMobile.Android.Resource.Attribute.light_icons;
			LegacyBar.Library.Resource.Attribute.separator = JabbrMobile.Android.Resource.Attribute.separator;
			LegacyBar.Library.Resource.Attribute.theme = JabbrMobile.Android.Resource.Attribute.theme;
			LegacyBar.Library.Resource.Attribute.title = JabbrMobile.Android.Resource.Attribute.title;
			LegacyBar.Library.Resource.Attribute.title_color = JabbrMobile.Android.Resource.Attribute.title_color;
			LegacyBar.Library.Resource.Color.Red = JabbrMobile.Android.Resource.Color.Red;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = JabbrMobile.Android.Resource.Color.actionbar_accentcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = JabbrMobile.Android.Resource.Color.actionbar_accentcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkblue = JabbrMobile.Android.Resource.Color.actionbar_accentcolor_darkblue;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = JabbrMobile.Android.Resource.Color.actionbar_accentcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = JabbrMobile.Android.Resource.Color.actionbar_accentcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_background_end = JabbrMobile.Android.Resource.Color.actionbar_background_end;
			LegacyBar.Library.Resource.Color.actionbar_background_end_alt = JabbrMobile.Android.Resource.Color.actionbar_background_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = JabbrMobile.Android.Resource.Color.actionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = JabbrMobile.Android.Resource.Color.actionbar_background_item_pressed_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = JabbrMobile.Android.Resource.Color.actionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = JabbrMobile.Android.Resource.Color.actionbar_background_item_pressed_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_start = JabbrMobile.Android.Resource.Color.actionbar_background_start;
			LegacyBar.Library.Resource.Color.actionbar_background_start_alt = JabbrMobile.Android.Resource.Color.actionbar_background_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_black = JabbrMobile.Android.Resource.Color.actionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = JabbrMobile.Android.Resource.Color.actionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_darkblue = JabbrMobile.Android.Resource.Color.actionbar_maincolor_darkblue;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = JabbrMobile.Android.Resource.Color.actionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = JabbrMobile.Android.Resource.Color.actionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = JabbrMobile.Android.Resource.Color.actionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = JabbrMobile.Android.Resource.Color.actionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkblue = JabbrMobile.Android.Resource.Color.actionbar_pressedcolor_darkblue;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = JabbrMobile.Android.Resource.Color.actionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = JabbrMobile.Android.Resource.Color.actionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_separator = JabbrMobile.Android.Resource.Color.actionbar_separator;
			LegacyBar.Library.Resource.Color.actionbar_separator_alt = JabbrMobile.Android.Resource.Color.actionbar_separator_alt;
			LegacyBar.Library.Resource.Color.actionbar_separator_black = JabbrMobile.Android.Resource.Color.actionbar_separator_black;
			LegacyBar.Library.Resource.Color.actionbar_separator_blue = JabbrMobile.Android.Resource.Color.actionbar_separator_blue;
			LegacyBar.Library.Resource.Color.actionbar_separator_darkblue = JabbrMobile.Android.Resource.Color.actionbar_separator_darkblue;
			LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = JabbrMobile.Android.Resource.Color.actionbar_separator_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = JabbrMobile.Android.Resource.Color.actionbar_separator_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_title = JabbrMobile.Android.Resource.Color.actionbar_title;
			LegacyBar.Library.Resource.Color.actionbar_title_alt = JabbrMobile.Android.Resource.Color.actionbar_title_alt;
			LegacyBar.Library.Resource.Color.actionbar_title_black = JabbrMobile.Android.Resource.Color.actionbar_title_black;
			LegacyBar.Library.Resource.Color.actionbar_title_blue = JabbrMobile.Android.Resource.Color.actionbar_title_blue;
			LegacyBar.Library.Resource.Color.actionbar_title_darkblue = JabbrMobile.Android.Resource.Color.actionbar_title_darkblue;
			LegacyBar.Library.Resource.Color.actionbar_title_darkgray = JabbrMobile.Android.Resource.Color.actionbar_title_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_title_lightgray = JabbrMobile.Android.Resource.Color.actionbar_title_lightgray;
			LegacyBar.Library.Resource.Color.black = JabbrMobile.Android.Resource.Color.black;
			LegacyBar.Library.Resource.Color.blue = JabbrMobile.Android.Resource.Color.blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_end = JabbrMobile.Android.Resource.Color.bottomactionbar_background_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = JabbrMobile.Android.Resource.Color.bottomactionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = JabbrMobile.Android.Resource.Color.bottomactionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_start = JabbrMobile.Android.Resource.Color.bottomactionbar_background_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = JabbrMobile.Android.Resource.Color.bottomactionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = JabbrMobile.Android.Resource.Color.bottomactionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkblue = JabbrMobile.Android.Resource.Color.bottomactionbar_maincolor_darkblue;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = JabbrMobile.Android.Resource.Color.bottomactionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = JabbrMobile.Android.Resource.Color.bottomactionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = JabbrMobile.Android.Resource.Color.bottomactionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = JabbrMobile.Android.Resource.Color.bottomactionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkblue = JabbrMobile.Android.Resource.Color.bottomactionbar_pressedcolor_darkblue;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = JabbrMobile.Android.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = JabbrMobile.Android.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_separator = JabbrMobile.Android.Resource.Color.bottomactionbar_separator;
			LegacyBar.Library.Resource.Color.bottomactionbar_title = JabbrMobile.Android.Resource.Color.bottomactionbar_title;
			LegacyBar.Library.Resource.Color.green = JabbrMobile.Android.Resource.Color.green;
			LegacyBar.Library.Resource.Color.grey = JabbrMobile.Android.Resource.Color.grey;
			LegacyBar.Library.Resource.Color.pager_black = JabbrMobile.Android.Resource.Color.pager_black;
			LegacyBar.Library.Resource.Color.pager_blue = JabbrMobile.Android.Resource.Color.pager_blue;
			LegacyBar.Library.Resource.Color.pager_darkblue = JabbrMobile.Android.Resource.Color.pager_darkblue;
			LegacyBar.Library.Resource.Color.pager_darkgray = JabbrMobile.Android.Resource.Color.pager_darkgray;
			LegacyBar.Library.Resource.Color.pager_lightgray = JabbrMobile.Android.Resource.Color.pager_lightgray;
			LegacyBar.Library.Resource.Color.red = JabbrMobile.Android.Resource.Color.red;
			LegacyBar.Library.Resource.Color.white = JabbrMobile.Android.Resource.Color.white;
			LegacyBar.Library.Resource.Color.yellow = JabbrMobile.Android.Resource.Color.yellow;
			LegacyBar.Library.Resource.Dimension.actionbar_accentheight = JabbrMobile.Android.Resource.Dimension.actionbar_accentheight;
			LegacyBar.Library.Resource.Dimension.actionbar_height = JabbrMobile.Android.Resource.Dimension.actionbar_height;
			LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = JabbrMobile.Android.Resource.Dimension.actionbar_home_item_width;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height = JabbrMobile.Android.Resource.Dimension.actionbar_item_height;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = JabbrMobile.Android.Resource.Dimension.actionbar_item_height_over;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = JabbrMobile.Android.Resource.Dimension.actionbar_item_height_overflow;
			LegacyBar.Library.Resource.Dimension.actionbar_item_width = JabbrMobile.Android.Resource.Dimension.actionbar_item_width;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = JabbrMobile.Android.Resource.Drawable.actionbar_back_indicator;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = JabbrMobile.Android.Resource.Drawable.actionbar_back_indicator_dark;
			LegacyBar.Library.Resource.Drawable.actionbar_background = JabbrMobile.Android.Resource.Drawable.actionbar_background;
			LegacyBar.Library.Resource.Drawable.actionbar_background_alt = JabbrMobile.Android.Resource.Drawable.actionbar_background_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_background_black = JabbrMobile.Android.Resource.Drawable.actionbar_background_black;
			LegacyBar.Library.Resource.Drawable.actionbar_background_blue = JabbrMobile.Android.Resource.Drawable.actionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_background_darkblue = JabbrMobile.Android.Resource.Drawable.actionbar_background_darkblue;
			LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = JabbrMobile.Android.Resource.Drawable.actionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = JabbrMobile.Android.Resource.Drawable.actionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn = JabbrMobile.Android.Resource.Drawable.actionbar_btn;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = JabbrMobile.Android.Resource.Drawable.actionbar_btn_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_black = JabbrMobile.Android.Resource.Drawable.actionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = JabbrMobile.Android.Resource.Drawable.actionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_darkblue = JabbrMobile.Android.Resource.Drawable.actionbar_btn_darkblue;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = JabbrMobile.Android.Resource.Drawable.actionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = JabbrMobile.Android.Resource.Drawable.actionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = JabbrMobile.Android.Resource.Drawable.actionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = JabbrMobile.Android.Resource.Drawable.actionbar_btn_normal_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = JabbrMobile.Android.Resource.Drawable.actionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = JabbrMobile.Android.Resource.Drawable.actionbar_btn_pressed_alt;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkblue = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background_darkblue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = JabbrMobile.Android.Resource.Drawable.bottomactionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkblue = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_darkblue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = JabbrMobile.Android.Resource.Drawable.bottomactionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = JabbrMobile.Android.Resource.Drawable.dropdown_btn_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = JabbrMobile.Android.Resource.Drawable.dropdown_btn_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = JabbrMobile.Android.Resource.Drawable.dropdown_disabled_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = JabbrMobile.Android.Resource.Drawable.dropdown_disabled_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = JabbrMobile.Android.Resource.Drawable.dropdown_focused_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = JabbrMobile.Android.Resource.Drawable.dropdown_focused_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = JabbrMobile.Android.Resource.Drawable.dropdown_normal_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = JabbrMobile.Android.Resource.Drawable.dropdown_normal_holo_light;
			LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = JabbrMobile.Android.Resource.Drawable.dropdown_pressed_holo_dark;
			LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = JabbrMobile.Android.Resource.Drawable.dropdown_pressed_holo_light;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow = JabbrMobile.Android.Resource.Drawable.ic_action_overflow;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = JabbrMobile.Android.Resource.Drawable.ic_action_overflow_dark;
			LegacyBar.Library.Resource.Id.actionbar_actions = JabbrMobile.Android.Resource.Id.actionbar_actions;
			LegacyBar.Library.Resource.Id.actionbar_home = JabbrMobile.Android.Resource.Id.actionbar_home;
			LegacyBar.Library.Resource.Id.actionbar_home_bg = JabbrMobile.Android.Resource.Id.actionbar_home_bg;
			LegacyBar.Library.Resource.Id.actionbar_home_btn = JabbrMobile.Android.Resource.Id.actionbar_home_btn;
			LegacyBar.Library.Resource.Id.actionbar_home_is_back = JabbrMobile.Android.Resource.Id.actionbar_home_is_back;
			LegacyBar.Library.Resource.Id.actionbar_home_logo = JabbrMobile.Android.Resource.Id.actionbar_home_logo;
			LegacyBar.Library.Resource.Id.actionbar_item = JabbrMobile.Android.Resource.Id.actionbar_item;
			LegacyBar.Library.Resource.Id.actionbar_progress = JabbrMobile.Android.Resource.Id.actionbar_progress;
			LegacyBar.Library.Resource.Id.actionbar_spinner = JabbrMobile.Android.Resource.Id.actionbar_spinner;
			LegacyBar.Library.Resource.Id.actionbar_title = JabbrMobile.Android.Resource.Id.actionbar_title;
			LegacyBar.Library.Resource.Id.actionbar_title_layout = JabbrMobile.Android.Resource.Id.actionbar_title_layout;
			LegacyBar.Library.Resource.Id.custom = JabbrMobile.Android.Resource.Id.custom;
			LegacyBar.Library.Resource.Id.holo_black = JabbrMobile.Android.Resource.Id.holo_black;
			LegacyBar.Library.Resource.Id.holo_blue = JabbrMobile.Android.Resource.Id.holo_blue;
			LegacyBar.Library.Resource.Id.holo_darkblue = JabbrMobile.Android.Resource.Id.holo_darkblue;
			LegacyBar.Library.Resource.Id.holo_gray = JabbrMobile.Android.Resource.Id.holo_gray;
			LegacyBar.Library.Resource.Id.holo_light = JabbrMobile.Android.Resource.Id.holo_light;
			LegacyBar.Library.Resource.Id.overflow_spinner = JabbrMobile.Android.Resource.Id.overflow_spinner;
			LegacyBar.Library.Resource.Id.screen = JabbrMobile.Android.Resource.Id.screen;
			LegacyBar.Library.Resource.Layout.actionbar = JabbrMobile.Android.Resource.Layout.actionbar;
			LegacyBar.Library.Resource.Layout.actionbar_item = JabbrMobile.Android.Resource.Layout.actionbar_item;
			LegacyBar.Library.Resource.Layout.blankspinner = JabbrMobile.Android.Resource.Layout.blankspinner;
			LegacyBar.Library.Resource.Layout.overflowactionbar_item = JabbrMobile.Android.Resource.Layout.overflowactionbar_item;
			LegacyBar.Library.Resource.Layout.spinneritem = JabbrMobile.Android.Resource.Layout.spinneritem;
			LegacyBar.Library.Resource.String.actionbar_activity_not_found = JabbrMobile.Android.Resource.String.actionbar_activity_not_found;
			LegacyBar.Library.Resource.Style.actionbar = JabbrMobile.Android.Resource.Style.actionbar;
			LegacyBar.Library.Resource.Style.actionbarhomeitem = JabbrMobile.Android.Resource.Style.actionbarhomeitem;
			LegacyBar.Library.Resource.Style.actionbarhomelogo = JabbrMobile.Android.Resource.Style.actionbarhomelogo;
			LegacyBar.Library.Resource.Style.actionbaritem = JabbrMobile.Android.Resource.Style.actionbaritem;
			LegacyBar.Library.Resource.Style.actionbarprogressbar = JabbrMobile.Android.Resource.Style.actionbarprogressbar;
			LegacyBar.Library.Resource.Style.clearbutton = JabbrMobile.Android.Resource.Style.clearbutton;
			LegacyBar.Library.Resource.Styleable.actionbar = JabbrMobile.Android.Resource.Styleable.actionbar;
			LegacyBar.Library.Resource.Styleable.actionbar_background = JabbrMobile.Android.Resource.Styleable.actionbar_background;
			LegacyBar.Library.Resource.Styleable.actionbar_background_item = JabbrMobile.Android.Resource.Styleable.actionbar_background_item;
			LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = JabbrMobile.Android.Resource.Styleable.actionbar_is_bottom;
			LegacyBar.Library.Resource.Styleable.actionbar_light_icons = JabbrMobile.Android.Resource.Styleable.actionbar_light_icons;
			LegacyBar.Library.Resource.Styleable.actionbar_separator = JabbrMobile.Android.Resource.Styleable.actionbar_separator;
			LegacyBar.Library.Resource.Styleable.actionbar_theme = JabbrMobile.Android.Resource.Styleable.actionbar_theme;
			LegacyBar.Library.Resource.Styleable.actionbar_title = JabbrMobile.Android.Resource.Styleable.actionbar_title;
			LegacyBar.Library.Resource.Styleable.actionbar_title_color = JabbrMobile.Android.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010016
			public const int MvxBind = 2130771990;
			
			// aapt resource value: 0x7f010018
			public const int MvxDropDownItemTemplate = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int MvxItemTemplate = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int MvxSource = 2130771993;
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int behindOffset = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int behindScrollScale = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int behindWidth = 2130771980;
			
			// aapt resource value: 0x7f010013
			public const int fadeDegree = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fadeEnabled = 2130771986;
			
			// aapt resource value: 0x7f010006
			public const int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int mode = 2130771976;
			
			// aapt resource value: 0x7f010015
			public const int selectorDrawable = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int selectorEnabled = 2130771988;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010010
			public const int shadowDrawable = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int shadowWidth = 2130771985;
			
			// aapt resource value: 0x7f010005
			public const int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			// aapt resource value: 0x7f01000e
			public const int touchModeAbove = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int touchModeBehind = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int viewAbove = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int viewBehind = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050041
			public const int Red = 2131034177;
			
			// aapt resource value: 0x7f050023
			public const int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f050033
			public const int actionbar_accentcolor_darkblue = 2131034163;
			
			// aapt resource value: 0x7f05001b
			public const int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f050032
			public const int actionbar_maincolor_darkblue = 2131034162;
			
			// aapt resource value: 0x7f05001a
			public const int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public const int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f050034
			public const int actionbar_pressedcolor_darkblue = 2131034164;
			
			// aapt resource value: 0x7f05001c
			public const int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f050036
			public const int actionbar_separator_darkblue = 2131034166;
			
			// aapt resource value: 0x7f05001e
			public const int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f050035
			public const int actionbar_title_darkblue = 2131034165;
			
			// aapt resource value: 0x7f05001d
			public const int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f05003b
			public const int black = 2131034171;
			
			// aapt resource value: 0x7f05003e
			public const int blue = 2131034174;
			
			// aapt resource value: 0x7f05000f
			public const int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public const int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f050037
			public const int bottomactionbar_maincolor_darkblue = 2131034167;
			
			// aapt resource value: 0x7f05001f
			public const int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public const int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050038
			public const int bottomactionbar_pressedcolor_darkblue = 2131034168;
			
			// aapt resource value: 0x7f050020
			public const int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f05003c
			public const int green = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int grey = 2131034175;
			
			// aapt resource value: 0x7f050029
			public const int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050039
			public const int pager_darkblue = 2131034169;
			
			// aapt resource value: 0x7f050021
			public const int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f05003d
			public const int red = 2131034173;
			
			// aapt resource value: 0x7f05003a
			public const int white = 2131034170;
			
			// aapt resource value: 0x7f050040
			public const int yellow = 2131034176;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_item_width = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_darkblue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_darkgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_background_lightgray = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_btn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn_alt = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_black = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_darkblue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_darkgray = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_lightgray = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_normal_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int actionbar_btn_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int actionbar_btn_pressed_alt = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_black = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_background_darkblue = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_background_darkgray = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_background_lightgray = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_black = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_blue = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_darkblue = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bottomactionbar_btn_darkgray = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bottomactionbar_btn_lightgray = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bottomactionbar_btn_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bottomactionbar_btn_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ButtonGlowLight = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dropdown_btn_holo_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dropdown_btn_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dropdown_disabled_holo_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dropdown_disabled_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dropdown_focused_holo_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dropdown_focused_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dropdown_normal_holo_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dropdown_normal_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dropdown_pressed_holo_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dropdown_pressed_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_down = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_down_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_left = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_left_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_overflow = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_overflow_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_refresh = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_refresh_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_right = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_right_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_search = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_search_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_share = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_action_share_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_action_sort = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_action_sort_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_action_up = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_action_up_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_menu_down = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_menu_left = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_menu_refresh = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_menu_right = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_menu_search = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_menu_up = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Icon = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int icon_accounts = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int icon_add = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int icon_delete = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int icon_exit = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int icon_green_circle_small = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icon_save = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int icon_settings = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int icon_users_grey = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icon_yellow_circle_small = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int jabbr_bg = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int jabbr_home_icon = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int SlidingMenuShadow = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int SlidingMenuShadowRight = 2130837586;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public const int MvxBindingTagUnique = 2130968587;
			
			// aapt resource value: 0x7f040018
			public const int actionbar = 2130968600;
			
			// aapt resource value: 0x7f040012
			public const int actionbar_actions = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_home = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int actionbar_home_bg = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int actionbar_home_btn = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int actionbar_home_is_back = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int actionbar_home_logo = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int actionbar_item = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int actionbar_progress = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int actionbar_spinner = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int actionbar_title = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int actionbar_title_layout = 2130968595;
			
			// aapt resource value: 0x7f04002f
			public const int checkBox1 = 2130968623;
			
			// aapt resource value: 0x7f040019
			public const int content_frame = 2130968601;
			
			// aapt resource value: 0x7f040000
			public const int custom = 2130968576;
			
			// aapt resource value: 0x7f04002a
			public const int editText1 = 2130968618;
			
			// aapt resource value: 0x7f04002c
			public const int editText2 = 2130968620;
			
			// aapt resource value: 0x7f04002e
			public const int editText3 = 2130968622;
			
			// aapt resource value: 0x7f040009
			public const int fullscreen = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int holo_black = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int holo_blue = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int holo_darkblue = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int holo_gray = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int holo_light = 2130968577;
			
			// aapt resource value: 0x7f04001c
			public const int imageView1 = 2130968604;
			
			// aapt resource value: 0x7f040023
			public const int imageView2 = 2130968611;
			
			// aapt resource value: 0x7f040006
			public const int left = 2130968582;
			
			// aapt resource value: 0x7f04001b
			public const int linearLayout1 = 2130968603;
			
			// aapt resource value: 0x7f040008
			public const int margin = 2130968584;
			
			// aapt resource value: 0x7f040030
			public const int menu_add = 2130968624;
			
			// aapt resource value: 0x7f040033
			public const int menu_connection = 2130968627;
			
			// aapt resource value: 0x7f040031
			public const int menu_delete = 2130968625;
			
			// aapt resource value: 0x7f040024
			public const int menu_frame = 2130968612;
			
			// aapt resource value: 0x7f040034
			public const int menu_leave_room = 2130968628;
			
			// aapt resource value: 0x7f040032
			public const int menu_save = 2130968626;
			
			// aapt resource value: 0x7f040028
			public const int mvxListViewAccounts = 2130968616;
			
			// aapt resource value: 0x7f04001a
			public const int mvxListViewMessages = 2130968602;
			
			// aapt resource value: 0x7f04001d
			public const int mvxListViewRooms = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int mvxListViewUsers = 2130968606;
			
			// aapt resource value: 0x7f040025
			public const int overflow_spinner = 2130968613;
			
			// aapt resource value: 0x7f040007
			public const int right = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int screen = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int selected_view = 2130968586;
			
			// aapt resource value: 0x7f040026
			public const int slidingmenumain = 2130968614;
			
			// aapt resource value: 0x7f040029
			public const int textView1 = 2130968617;
			
			// aapt resource value: 0x7f04002b
			public const int textView2 = 2130968619;
			
			// aapt resource value: 0x7f04002d
			public const int textView3 = 2130968621;
			
			// aapt resource value: 0x7f040022
			public const int textViewMessageBody = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int textViewMessageUser = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int textViewRoomName = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int textViewServer = 2130968608;
			
			// aapt resource value: 0x7f040027
			public const int userlist_frame = 2130968615;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Content_Frame = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_Chat = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_Empty = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_UserList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem_Account = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListItem_Chat = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListItem_Menu_Room = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ListItem_Menu_User = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ListItem_Room = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Menu_Frame = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int overflowactionbar_item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int slidingmenumain = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int spinneritem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int UserList_Frame = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int View_Accounts = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int View_EditAccount = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int View_RoomList = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int AccountsMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int EditAccountMenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int HomeMenu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int Hello = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int actionbar_activity_not_found = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int library_name = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int menu_string_delete = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int menu_string_down = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int menu_string_exit = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int menu_string_left = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int menu_string_refresh = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int menu_string_right = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int menu_string_save = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int menu_string_search = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int menu_string_sort = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int menu_string_up = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int some_title = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080006
			public const int MyTheme = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771990};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771993};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771991,
					2130771992};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SlidingMenu = new int[]
			{
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			public static int[] actionbar = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
