#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JabbrMobile.Android.Resource", IsApplication=true)]

namespace JabbrMobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			SlidingMenuSharp.Resource.Attribute.behindOffset = JabbrMobile.Android.Resource.Attribute.behindOffset;
			SlidingMenuSharp.Resource.Attribute.behindScrollScale = JabbrMobile.Android.Resource.Attribute.behindScrollScale;
			SlidingMenuSharp.Resource.Attribute.behindWidth = JabbrMobile.Android.Resource.Attribute.behindWidth;
			SlidingMenuSharp.Resource.Attribute.fadeDegree = JabbrMobile.Android.Resource.Attribute.fadeDegree;
			SlidingMenuSharp.Resource.Attribute.fadeEnabled = JabbrMobile.Android.Resource.Attribute.fadeEnabled;
			SlidingMenuSharp.Resource.Attribute.mode = JabbrMobile.Android.Resource.Attribute.mode;
			SlidingMenuSharp.Resource.Attribute.selectorDrawable = JabbrMobile.Android.Resource.Attribute.selectorDrawable;
			SlidingMenuSharp.Resource.Attribute.selectorEnabled = JabbrMobile.Android.Resource.Attribute.selectorEnabled;
			SlidingMenuSharp.Resource.Attribute.shadowDrawable = JabbrMobile.Android.Resource.Attribute.shadowDrawable;
			SlidingMenuSharp.Resource.Attribute.shadowWidth = JabbrMobile.Android.Resource.Attribute.shadowWidth;
			SlidingMenuSharp.Resource.Attribute.touchModeAbove = JabbrMobile.Android.Resource.Attribute.touchModeAbove;
			SlidingMenuSharp.Resource.Attribute.touchModeBehind = JabbrMobile.Android.Resource.Attribute.touchModeBehind;
			SlidingMenuSharp.Resource.Attribute.viewAbove = JabbrMobile.Android.Resource.Attribute.viewAbove;
			SlidingMenuSharp.Resource.Attribute.viewBehind = JabbrMobile.Android.Resource.Attribute.viewBehind;
			SlidingMenuSharp.Resource.Id.fullscreen = JabbrMobile.Android.Resource.Id.fullscreen;
			SlidingMenuSharp.Resource.Id.left = JabbrMobile.Android.Resource.Id.left;
			SlidingMenuSharp.Resource.Id.margin = JabbrMobile.Android.Resource.Id.margin;
			SlidingMenuSharp.Resource.Id.right = JabbrMobile.Android.Resource.Id.right;
			SlidingMenuSharp.Resource.Id.selected_view = JabbrMobile.Android.Resource.Id.selected_view;
			SlidingMenuSharp.Resource.Id.slidingmenumain = JabbrMobile.Android.Resource.Id.slidingmenumain;
			SlidingMenuSharp.Resource.Layout.slidingmenumain = JabbrMobile.Android.Resource.Layout.slidingmenumain;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu = JabbrMobile.Android.Resource.Styleable.SlidingMenu;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindOffset;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindScrollScale;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = JabbrMobile.Android.Resource.Styleable.SlidingMenu_behindWidth;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = JabbrMobile.Android.Resource.Styleable.SlidingMenu_fadeDegree;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = JabbrMobile.Android.Resource.Styleable.SlidingMenu_fadeEnabled;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = JabbrMobile.Android.Resource.Styleable.SlidingMenu_mode;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = JabbrMobile.Android.Resource.Styleable.SlidingMenu_selectorDrawable;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = JabbrMobile.Android.Resource.Styleable.SlidingMenu_selectorEnabled;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = JabbrMobile.Android.Resource.Styleable.SlidingMenu_shadowDrawable;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = JabbrMobile.Android.Resource.Styleable.SlidingMenu_shadowWidth;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = JabbrMobile.Android.Resource.Styleable.SlidingMenu_touchModeAbove;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = JabbrMobile.Android.Resource.Styleable.SlidingMenu_touchModeBehind;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = JabbrMobile.Android.Resource.Styleable.SlidingMenu_viewAbove;
			SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = JabbrMobile.Android.Resource.Styleable.SlidingMenu_viewBehind;
			JabbrMobile.Common.Resource.String.library_name = JabbrMobile.Android.Resource.String.library_name;
			JabbR.Client.Android.Resource.String.library_name = JabbrMobile.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int MvxBind = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int MvxDropDownItemTemplate = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int MvxItemTemplate = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int MvxSource = 2130771985;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int MvxBindingTagUnique = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int content_frame = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int fullscreen = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int left = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int margin = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int menu_frame = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int right = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int selected_view = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int slidingmenumain = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Content_Frame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu_Frame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int slidingmenumain = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771982};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771985};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SlidingMenu = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
